--1 
SELECT Manager_ID, COUNT (1)
FROM DEPARTMENTS dep JOIN EMPLOYESS emp ON dep.Manager_ID = emp.Manager_ID 
GROUP BY emp.Manager_ID 
HAVING COUNT (1)>6
--2 
SELECT dep. DEPARTMENT_NAME,  MIN(SALARY - (SALARY * COMMISSION_PCT / 100)) AS Min_Salary,
	                          MAX(SALARY - (SALARY * COMMISSION_PCT / 100)) AS Max_Salary
FROM DEPARTMENTS dep JOIN EMPLOYESS ON dep. DEPARTMENT_ID=emp.DEPARTMENT_ID
GROUP BY dep. DEPARTMENT_ID
--3
SELECT TOP 1 WITH TIES reg.REGION_NAME
FROM EMPLOYEES emp JOIN DEPARTMENTS dep ON emp.DEPARTMENT_ID=dep.DEPARTMENT_ID
JOIN LOCATIONS loc ON loc.LOCATION_ID=dep.LOCATION_ID
JOIN COUNTRIES c ON c.COUNTRY_ID=loc.COUNTRY_ID
JOIN REGIONS reg   ON reg.REGION_ID=c.REGION_ID
GROUP BY reg. REGION_NAME
ORDER BY COUNT(EMPLOYEE_ID) DESC
 --4
SELECT DEPARTMENT_NAME, 
(AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) / AVG(SALARY) OVER ()) * 100 AS Difference
FROM EMPLOYEES emp
JOIN DEPARTMENTS dep ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID

--5
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID, DATEDIFF(YEAR, START_DATE, ISNULL(end_date, GETDATE())) as Period
FROM EMPLOYEES emp JOIN JOB_HISTORY jh ON emp.EMPLOYEE_ID=jh.EMPLOYEE_ID
WHERE DATEDIFF(YEAR, START_DATE, ISNULL(end_date, GETDATE()))>10

--6
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM
(
SELECT FIRST_NAME, LAST_NAME, SALARY, DENSE_RANK() OVER (ODER BY SALARY DESC) AS SalaryRank
 FROM EMPLOYEES
 ) emp
 WHERE SalaryRank BETWEEN 5 and 10